name : Mygit
on:
  push:
    branches:
      - master
      
jobs:
  my_testing:
    runs_on : ubuntu-latest
    steps:
    - name : kkkkk
      run : ls -la
    - name : kkdfkflsls
      uses : actions/checkout@v1
    - name : lfksfsffsfs
      run : ls -la
    
